version: '3.8'

services:
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.test
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate_limiter_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: